### ISSUE TITLE
Valid plan rejected for no clear reason

### ISSUE THREAD

**Issue by mabdula** [KCL-Planning/VAL#29]
In the attached zip file there is a domain, instance and a plan that seems valid (INVAL says so), while VAL says that it is not. The only explanation I can think of is that the action defined in the domain has no preconditions.

[bug3.zip](https://github.com/KCL-Planning/VAL/files/2066133/bug3.zip)

Cheers,
Mohammad

**Comment by DerekLong101** [comment]
Thanks for these. I will take a look and get back to you.


Sent from Samsung tablet.
-------- Original message --------From: mabdula <notifications@github.com> Date: 03/06/2018  17:27  (GMT+00:00) To: KCL-Planning/VAL <VAL@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [KCL-Planning/VAL] Valid plan rejected for no clear reason (#29) 
In the attached zip file there is a domain, instance and a plan that seems valid (INVAL says so), while VAL says that it is not. The only explanation I can think of is that the action defined in the domain has no preconditions.
bug3.zip
Cheers,

Mohammad

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/KCL-Planning/VAL/issues/29","url":"https://github.com/KCL-Planning/VAL/issues/29","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/KCL-Planning/VAL","title":"KCL-Planning/VAL","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/KCL-Planning/VAL"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Valid plan rejected for no clear reason (#29)"}],"action":{"name":"View Issue","url":"https://github.com/KCL-Planning/VAL/issues/29"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Valid plan rejected for no clear reason (#29)",
"sections": [
{
"text": "",
"activityTitle": "**mabdula**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@mabdula",
"facts": [
{
"name": "Repository: ",
"value": "KCL-Planning/VAL"
},
{
"name": "Issue #: ",
"value": 29
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"KCL-Planning/VAL\",\n\"issueId\": 29,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"KCL-Planning/VAL\",\n\"issueId\": 29\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/KCL-Planning/VAL/issues/29"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 341873591\n}"
}
],
"themeColor": "26292E"
}

**Comment by DerekLong101** [comment]
This one is not very interesting, either - the precondition field is not optional so the parser fails in the action and then gets confused by the rest of the input.

________________________________

**Comment by DerekLong101** [comment]
Yes, quite right, VAL does not accept a missing precondition field. The rule in the parser is:


c_action_def :
    OPEN_BRAC  ACTION NAME  c_args_head OPEN_BRAC c_typed_var_list CLOSE_BRAC
    PRE c_pre_goal_descriptor
    EFFECTS c_effect
    CLOSE_BRAC
|   OPEN_BRAC ACTION error CLOSE_BRAC
;

Kovacs' syntax was his own effort to synthesise a grammar and postdates the construction of VAL by very many years. The PDDL syntax in the original PDDL 2.1 paper, extended to account for PDDL3.1 (constraints), PDDL2.2 (TILs, derived predicates) and TIFs (analogous to TILs, but assigning values to numeric fluents), PDDL+ (events, processes) are all handled. The PDDL2.1 paper is confusing in that it specifies fields for durative actions (conditions and effects) as required, but for actions as optional. So, this specification suggests that VAL should be permissive about preconditions. However, it is not.

I think that the PDDL2.1 BNF is about as close as you will get, other than scrutiny of the pddl.yacc file. The main issues of divergence will be in the corner cases (such as you identify).

Cheers

Derek

________________________________

**Comment by mabdula** [comment]
I see, thanks a lot for your response.

Cheers
Mohammad

**Comment by guicho271828** [comment]
@mabdula @DerekLong101 This is fixed in #25

**Comment by guicho271828** [comment]
should be closed

**Comment by DerekLong101** [comment]
As noted.
