### ISSUE TITLE
Dead project or VAL2?

### ISSUE THREAD

**Issue by guicho271828** [KCL-Planning/VAL#33]
If there is no plan/manpower to merge PRs, I suggest assigning several contributors and give them a push access.
Related : https://github.com/pypa/warehouse/issues/1506

I also suggest adding a proper unit testing , coupled with CI services integration (Travis CI etc... which are free!).
This should ensure that the project builds fine on various OSes and also that there are no regression prior to merging when someone raised a PR.

**Comment by guicho271828** [comment]
Or we could set up a different repo like named VAL2 and claim that it is maintained

**Comment by DerekLong101** [comment]
Thanks for the comments, Masataro. I have been rather slack at worrying about this repo because I am working in industry, where we are using this code base a lot, but I have been working on it in local repositories. I intend to push back some of the updates and changes.


Let me think about the best way to proceed. I'd rather not see forked projects from the main branch, to be honest, because it will make maintaining coherence much harder.


Cheers


Derek

________________________________

**Comment by jan-dolejsi** [comment]
A major update is coming very soon via a pull request. We've worked out the agreement to switch the license, cleaned up the structure, added continuous integration (providing binaries for Linux, Windows and Mac) and added several other nifty tools based on Val as a library.

**Comment by jan-dolejsi** [comment]
We are taking a little bit longer to set the continuous integration right and to ensure the binaries work on Linux and MacOS without having to set the library path.
