### ISSUE TITLE
parse tree visitor bug?

### ISSUE THREAD

**Issue by morlic** [KCL-Planning/VAL#36]
The type of the param for visit_class_symbol is const_symbol.. a c/p bug?

https://github.com/KCL-Planning/VAL/blob/master/include/VisitController.h#L41

**Comment by DerekLong101** [comment]
The class structures are not a formal part of PDDL and were included as an experimental development. Maria and I have been using them in some ideas we are exploring. Because they are not a formal extension, they got patched in on top of existing structures to save effort - the parse category for the names of classes was simply a reuse of a const symbol for convenience (they play no role in anything anyone else is doing, to the best of my knowledge). At some point, a formal proposal for the language enhancement might be made and then the parsing might be tidied up.


- Derek

________________________________

**Comment by morlic** [comment]
Thanks for the quick response.. I am trying to make popf and optic compile on mac/clang, one thing I did was to update the parser there with latest from VAL - did you make any attempts to compile with clang?

**Comment by DerekLong101** [comment]
Good question. VAL has been compiled with a variety of compilers - I personally have not used clang, and I cannot recall a specific reference to anyone using it, but it has been compiled on other platforms. Clang should be pretty good, I'd have thought, but it might be fussier about some of POPF/VAL dated/sloppy C++. I suspect that changing the parser for POPF/OPTIC might create some minor issues but I'm not sure - I have a version of POPF that is quite modified and that compiles with the updated parser (actually, one that includes a few other bits and pieces) and some other stuff, but I can't release it, so tha's not much use to you. I do have a version of POPF that compiles under Mingw and I know that there are versions that compile on MacOS.


Cheers


Derek

________________________________

**Comment by DerekLong101** [comment]
I am closing this because the latest Master should compile cleanly in this environment. Please reopen an issue if it does not.

**Comment by morlic** [comment]
Confirmed, it compiles cleanly with just some C++ warnings (conversion from string to char*, register storage class deprecated, comparing bool with int).
