### ISSUE TITLE
Ability to output all intermediate states during plan execution

### ISSUE THREAD

**Issue by aindilis** [KCL-Planning/VAL#47]
I have been struggling for some of my projects to be able to compute the complete state (all fluents and function values, and maybe more) before and after all time points (in temporal plans) or all steps (in sequential).  It would be an absolute godsend if you could please add a command line option to print the plan steps and the corresponding intermediate state.  Sorry for my lack of articulation, I can provide an example if my meaning isn't clear.  I am trying to write an interactive execution monitor, and it needs to know whether the preconditions are satisfied in the real world, and afterwards whether the effects are satisfied in the real world.  I haven't had any success in trying to compute the intermediate state on my own, or to edit VAL to output it.

**Comment by DerekLong101** [comment]
This can be achieved using VALSTEP, which is an application in the archive. You can request that VALSTEP deliver intermediate states (including as PDDL problem files or simply as states or state deltas). Have a look at the VALSTEP code because it will also show how to achieve the effects programatically, if VALSTEP is not quite what you need.
